//// GET
### Returns a default message - no data.
GET http://rr-roster.onrender.com/ HTTP/1.1


//////////////////////////////////////////////////////
////////////////  ROSTER COLLECTION  /////////////////
//////////////////////////////////////////////////////

//// GET ////
### Read and return all contacts in DB.
GET http://rr-roster.onrender.com/roster HTTP/1.1

### Read and return a single document specified by ID.
GET http://rr-roster.onrender.com/roster/6524c94222544809fd4f28b0 HTTP/1.1


//// POST ////
### Create a new document and add to the collection.
POST http://rr-roster.onrender.com/roster HTTP/1.1
content-type: application/json

{
  "reportingMark": "TEST",
  "carNumber": "999444",
  "aarCarType": "XM",
  "carLength": 480,
  "carHeight": 186,
  "color": "Brown",
  "ltWeight": 50000,
  "ldLimit": 150000,
  "capacity": 125000,
  "units": "pounds",
  "builtMonth": 1,
  "builtYear": 1952
}

//// PUT ////
### Update/change a specific document specified by ID.
PUT http://rr-roster.onrender.com/roster/652a260d12801b642d315b92 HTTP/1.1
content-type: application/json

{
  "reportingMark": "TEST",
  "carNumber": "654321",
  "aarCarType": "XM",
  "carLength": 480,
  "carHeight": 186,
  "color": "Blue",
  "ltWeight": 50000,
  "ldLimit": 150000,
  "capacity": 125000,
  "units": "pounds",
  "builtMonth": 8,
  "builtYear": 1960
}

//// DELETE ////
### Delete a specific document specified by ID. 
DELETE http://rr-roster.onrender.com/roster/652a260d12801b642d315b92 HTTP/1.1
content-type: application/json



////////////////////////////////////////////////////////
////////////////  RAILROAD COLLECTION  /////////////////
////////////////////////////////////////////////////////

//// GET ////
### Read and return all contacts in DB.
GET http://rr-roster.onrender.com/railroad HTTP/1.1

### Read and return a single document specified by ID.
GET http://rr-roster.onrender.com/railroad/652b192012801b642d315b96 HTTP/1.1


//// POST ////
### Create a new document and add to the collection.
POST http://rr-roster.onrender.com/railroad HTTP/1.1
content-type: application/json

{
  "reportingMark": "TEST",
  "railroadName": "Test Every Single Track"
}

//// PUT ////
### Update/change a specific document specified by ID.
PUT http://rr-roster.onrender.com/railroad/652b36118c25e9a1e630c416 HTTP/1.1
content-type: application/json

{
  "reportingMark": "TEOT",
  "railroadName": "Test Every Other Track"
}

//// DELETE ////
### Delete a specific document specified by ID. 
DELETE http://rr-roster.onrender.com/railroad/652b36118c25e9a1e630c416 HTTP/1.1
content-type: application/json


